AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yorkshire-golf

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:

  YorkshireGolfApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Domain:
        DomainName: 'www.yorkshiregolf.life'
        CertificateArn: '{{resolve:ssm:/YorkshireGolf/Prod/CertificateArn}}'

  YorkshireGolfFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: golf.App::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HomePage:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: YorkshireGolfApi

Outputs:
  YorkshireGolfFunctionApi:
    Description: API Gateway endpoint URL for Prod stage for Yorkshire Golf function
    Value: !Sub "https://${YorkshireGolfApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  YorkshireGolfFunctionFunction:
    Description: Yorkshire Golf Function ARN
    Value: !GetAtt YorkshireGolfFunction.Arn
  YorkshireGolfFunctionFunctionIamRole:
    Description: Implicit IAM Role created for Yorkshire Golf function
    Value: !GetAtt YorkshireGolfFunction.Arn
