spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

golf:
  app:
    base-url: ${APP_BASE_URL:https://yorkshiregolf.life}
  google-maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
