spring:
  mail:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

golf:
  app:
    base-url: http://localhost:8080
  google-maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
