spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

golf:
  app:
    base-url: ${APP_BASE_URL:https://yorkshiregolf.life}
  google-maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
